'use strict';const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),A=require('./logic.js');
class El{constructor(value=''){this.value=value;this.events={};this.hidden=false;this.disabled=false;this.checked=false;this.files=[];this.textContent='';}addEventListener(n,f){this.events[n]=f;}async fire(n='click'){return this.events[n]({preventDefault(){}});}}
function page(kind){let ids=['input','before','after','file','before-file','after-file','topic','synthetic','need','help','form','sample','result','error','report','csv-save','txt-save'];let e=Object.fromEntries(ids.map(id=>[id,new El()]));e.topic.value='story';let blobs=[];vm.runInNewContext(fs.readFileSync(__dirname+'/app.js','utf8'),{AliasChecks:A,Blob,URL:{createObjectURL:b=>{blobs.push(b);return 'blob:test';},revokeObjectURL(){}},setTimeout:fn=>fn(),document:{body:{dataset:{job:kind}},getElementById:id=>e[id],createElement:()=>({click(){}})}});return {e,blobs};}
(async()=>{let checks=0;for(const kind of ['permission','migration','batches']){let {e,blobs}=page(kind);await e.sample.fire();await e.form.fire('submit');assert.equal(e.result.hidden,false);assert.equal(e['csv-save'].disabled,false);await e['csv-save'].fire();assert.ok((await blobs.at(-1).text()).includes('alias'));await e['txt-save'].fire();assert.ok((await blobs.at(-1).text()).includes('架空ID'));checks+=3;
 let field=kind==='migration'?e.after:e.input;field.value='broken';await field.fire('input');assert.equal(e.result.hidden,true);assert.equal(e['csv-save'].disabled,true);await e.form.fire('submit');assert.equal(e.result.hidden,true);checks+=2;
 await e.sample.fire();e.synthetic.checked=false;await e.form.fire('submit');assert.equal(e['csv-save'].disabled,true);checks++;
 await e.sample.fire();await e.form.fire('submit');assert.equal(e.help.hidden,true);e.need.checked=true;await e.need.fire('change');assert.equal(e.help.hidden,false);checks++;
 let file=kind==='migration'?e['after-file']:e.file;file.files=[{size:4,text:async()=> 'oops'}];await file.fire('change');assert.equal(e.result.hidden,true);assert.equal(e['txt-save'].disabled,true);checks++;
 let resolve;const valid=kind==='migration'?e.after.value:e.input.value;file.files=[{size:valid.length,text:()=>new Promise(r=>resolve=r)}];let importing=file.fire('change');field.value='new-edit';await field.fire('input');resolve(valid);await importing;assert.equal(field.value,'new-edit');checks++;
 }console.log(JSON.stringify({checks,status:'passed',route:'Three DOM event harnesses; actual CSV/TXT Blob reads; visual browser QA remains parent'}));})().catch(e=>{console.error(e);process.exitCode=1;});
