'use strict';const assert=require('node:assert/strict'),A=require('./logic.js');const h='alias,permission,withdrawn,topics\n',b='campaign,batch,alias,topic,permission,withdrawn,topics\n';let checks=0;function test(n,f){f();checks++;console.log('ok '+n);}
test('permission candidates, withdrawn and unknown separate',()=>{let r=A.permission(A.records(h+'p001,yes,no,story\np002,yes,yes,story\np003,unknown,no,story\np004,yes,no,notes\np005,yes,unknown,story\n'),'story');assert.deepEqual(r.summary,{declared_candidate:1,stop:2,unknown:2});});
test('unknown is explicit, never blank or zero',()=>{for(const v of ['','0','true','false'])assert.throws(()=>A.records(h+'p001,'+v+',no,story'));});
test('real names and emails rejected',()=>{for(const v of ['Alice','alice@example.com','001','p01','p123456'])assert.throws(()=>A.records(h+v+',yes,no,story'));});
test('duplicates/missing/extra headers rejected before output',()=>{for(const s of [h+'p001,yes,no,story\np001,yes,no,story','alias,permission,withdrawn\np001,yes,no',h+'p001,yes,no,story,secret'])assert.throws(()=>A.records(s));});
test('BOM quoted CRLF recognized and malformed CSV rejected',()=>{assert.equal(A.records('\uFEFF'+h.replace('\n','\r\n')+'"p001",yes,no,"story|notes"\r\n')[0].topics,'story|notes');for(const s of [h+'"p001,yes,no,story',h+'"p001"x,yes,no,story',h+'p00"1,yes,no,story'])assert.throws(()=>A.records(s));});
test('limits bytes and rows',()=>{assert.throws(()=>A.records(' '.repeat(A.MAX_BYTES+1)));assert.throws(()=>A.records(h+Array.from({length:501},(_,i)=>'p'+String(i).padStart(3,'0')+',yes,no,story').join('\n')));});
test('withdrawal never reactivated after migration',()=>{let r=A.migration(A.records(h+'p001,yes,yes,story'),A.records(h+'p001,yes,no,story'),'story');assert.equal(r.rows[0].classification,'stop');assert.ok(r.rows[0].flags.includes('withdrawal_lost_hold'));});
test('missing and added records visible, not zero',()=>{let r=A.migration(A.records(h+'p001,yes,no,story'),A.records(h+'p002,yes,no,story'),'story');assert.equal(r.rows[0].classification,'stop');assert.ok(r.rows[0].flags.includes('missing_after'));assert.equal(r.rows[1].classification,'unknown');assert.ok(r.rows[1].flags.includes('added_alias_review'));});
test('topic/permission changes held for review',()=>{let r=A.migration(A.records(h+'p001,unknown,no,notes'),A.records(h+'p001,yes,no,story|notes'),'story');assert.equal(r.rows[0].classification,'unknown');assert.deepEqual(r.rows[0].flags,['permission_changed_review','topics_changed_review']);});
test('unchanged declared candidate stays qualified by owner only',()=>{const rows=A.records(h+'p001,yes,no,story');let r=A.migration(rows,rows,'story');assert.equal(r.rows[0].classification,'declared_candidate');assert.ok(r.limits.includes('実サービス'));});
test('same campaign/topic overlap and separate campaign distinction',()=>{let r=A.batches(A.records(b+'c001,b001,p001,story,yes,no,story|notes\nc001,b002,p001,notes,yes,no,story|notes\nc002,b001,p001,story,yes,no,story|notes',true));assert.equal(r.summary.repeated_campaign_alias_groups,1);assert.equal(r.summary.repeated_candidate_rows,2);assert.equal(r.rows[2].overlap.length,0);});
test('unknown and withdrawn excluded from duplication candidates',()=>{let r=A.batches(A.records(b+'c001,b001,p001,story,unknown,no,story\nc001,b002,p001,story,unknown,no,story\nc001,b001,p002,notes,yes,yes,notes',true));assert.equal(r.summary.repeated_candidate_rows,0);assert.equal(r.summary.unknown,2);assert.equal(r.summary.stop,1);});
test('same batch exact duplicate and conflicting alias states fail',()=>{for(const s of [b+'c001,b001,p001,story,yes,no,story\nc001,b001,p001,story,yes,no,story',b+'c001,b001,p001,story,yes,no,story\nc001,b002,p001,story,yes,yes,story'])assert.throws(()=>A.records(s,true));});
test('free CSV/TXT outputs retain reasons, no auto-send instructions',()=>{let r=A.permission(A.records(h+'p001,unknown,no,story'),'story');assert.ok(A.csv(r).includes('"unknown"'));assert.ok(A.txt(r).includes('送信しません'));});
console.log(JSON.stringify({checks,status:'passed'}));
